"""empty message

Revision ID: 54bf9d69da3c
Revises: 136a9cb9397b
Create Date: 2017-12-22 11:52:05.931263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54bf9d69da3c'
down_revision = '136a9cb9397b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('obj', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'obj')
    # ### end Alembic commands ###
