"""empty message

Revision ID: b1a81022c365
Revises: c840d63b1158
Create Date: 2017-12-27 11:45:22.041588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a81022c365'
down_revision = 'c840d63b1158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author')
    # ### end Alembic commands ###
